apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-depl
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets                   # Name you gave the secrets component
              key: dbUsername                         # Key specified inside the data property of the secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets                   # Name you gave the secrets component
              key: dbPassword                         # Key specified inside the data property of the secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb                # Label of our deployment
  ports:
    - protocol: TCP
      port: 27017               # We use the same port in our service for convenience
      targetPort: 27017         # Same port as we opened in our pod